version: "3.9"
services:
  db:
    image: postgres:13.1-alpine
    container_name: demo-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demo

  web:
    build: .
    ports:
      - "8080:8080"
    container_name: demo-web
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/demo
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password